# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:

  build:
    docker:
      - image: buildpack-deps:18.04-curl

    steps:
      - run: apt-get update
      - run: apt install git cmake build-essential -y
      - run: apt-get install freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev -y
      - run:
          name: "Install SFML dependencies"
          command: apt install libpthread-stubs0-dev libx11-dev libxrandr-dev libfreetype6-dev libopenal-dev libudev-dev libvorbis-dev -y
      - run:
          name: "Install test dependencies"
          command: apt install valgrind -y
      - run:
          name: "Install SFML"
          command: mkdir SFML && cd SFML && git clone --single-branch --branch 2.5.x https://github.com/SFML/SFML.git && cd SFML && cmake . && make && make install && cd ../..
